# Generated by Django 4.2.4 on 2023-09-01 18:55

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(default="Kano", max_length=180, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="NG", max_length=2, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+2347037052532",
                max_length=30,
                region=None,
                verbose_name="phone number",
            ),
        ),
    ]
